language: clojure

lein: lein2

sudo: required

group: edge

jdk:
- openjdk6
- openjdk7
- oraclejdk7
- oraclejdk8

matrix:
  allow_failures:
  - jdk: oraclejdk7
  - jdk: oraclejdk8

after_script: dpkg --get-selections | grep -v deinstall | awk '{ print $1 }'
